[WIP] Rizzo gem
ghoneycutt/rizzo pull request #8
Opened 2017-08-10 22:45 UTC by jeffmccune

Refactor existing rizzo code into a Ruby gem, suitable for including in a
control repo Gemfile.

2017-08-11 15:36 UTC, ghoneycutt commented on lib/rizzo/version.rb
> +  def self.version
why is this here and in `lib/rizzo.rb` ?

2017-08-11 15:46 UTC, ghoneycutt commented
Have not heard back from the maintainer of the rizzo rubygem, so grabbed the name `rzo`.

https://rubygems.org/gems/rzo

2017-08-11 15:49 UTC, ghoneycutt commented
for our first version, we just need the functionality of writing out the Vagrantfile from a template to the first (top) layer control repo's directory.

2017-08-11 15:53 UTC, jeffmccune commented
Got it, should have that implemented by Monday.

2017-08-11 18:00 UTC, jeffmccune commented on lib/rizzo/version.rb
> +  def self.version
It should just be in the version.

2017-08-11 19:29 UTC, jeffmccune commented on README.md
> +`spec/spec_helper.rb` will need at least the following.
This is intended to be the spec_helper of the top level control repo, yes?

2017-08-11 21:50 UTC, ghoneycutt commented on README.md
> +`spec/spec_helper.rb` will need at least the following.
yeah, as part of the effort to allow for ensuring that we can compile catalogs for each role

2017-08-14 13:58 UTC, jeffmccune commented
@ghoneycutt Would love to get your feedback on this, the `Vagrantfile` generation has been implemented.

What do you think about adding `rzo` as a Gem dependency inside Puppetdata's Gemfile?  Here's how it works now:

First, add the dependency to `puppetdata/Gemfile`

```diff
diff --git a/Gemfile b/Gemfile
index 572f681..5c2f3b0 100644
--- a/Gemfile
+++ b/Gemfile
@@ -20,6 +20,7 @@ gem 'puppet-lint-undef_in_function-check'
 gem 'puppet-lint-unquoted_string-check'
 gem 'puppet-lint-variable_contains_upcase'
 gem 'puppet-syntax'
+gem 'rzo', git: 'https://github.com/jeffmccune/rizzo.git', branch: 'turn_into_gem'

 gem 'serverspec', :require => false
 gem 'vagrant-wrapper', :require => false
```

Install the gems with `bundle install --path .bundle/gem/`

Then generate the Vagrantfile:

```
bundle exec rzo generate > Vagrantfile
```

Then boot the VM's as normal:

```
vagrant up infra-puppetfourca
```

Here's what is currently implemented:

```
be rizzo --help
usage: rizzo [GLOBAL OPTIONS] SUBCOMMAND [ARGS]
Sub Commands:

  generate     Initialize Vagrantfile in top control repo

Global options: (Note, command line arguments supersede ENV vars in {}'s)
  -l, --logto=<s>     Log file to write to or keywords STDOUT, STDERR {RZO_LOGTO} (default: STDERR)
  -s, --syslog        Log to syslog
  -v, --verbose       Set log level to INFO
  -d, --debug         Set log level to DEBUG
  -c, --config=<s>    Rizzo config file {RZO_CONFIG} (default: ~/.rizzo.json)
  -e, --version       Print version and exit
  -h, --help          Show this message
```

```
bundle exec rizzo generate --help
rizzo generate options:
  -o, --vagrantfile=<s>    Output Vagrantfile (default: STDOUT)
  -h, --help               Show this message
```

2017-08-15 19:27 UTC, ghoneycutt commented
`rzo generate` should create the Vagrantfile instead of having to run `bundle exec rzo generate > Vagrantfile`

2017-08-15 19:29 UTC, ghoneycutt commented on .travis.yml
>    - 2.1.9
Which ruby versions should we support? 2.1.9 is what puppet4 uses and puppet5 is currently on 2.4.1. Should we support both? others?

2017-08-15 22:50 UTC, jeffmccune commented on .travis.yml
>    - 2.1.9
Let's support the same ruby version shipping in the AIO package of the Puppet Agent the customer support.  So we can start with Puppet 4, Puppet 5 with MRI 2.1.9 and 2.4.1 and add future MRI versions for Puppet 6 onward.

2017-08-16 21:23 UTC, ghoneycutt commented on .travis.yml
>    - 2.1.9
Cool. Let's change this to test against 2.1.9 and 2.4.1.

2017-08-16 21:24 UTC, ghoneycutt commented on .travis.yml
> +before_install: gem install bundler -v 1.15.3
Should not have to install bundler as it will be there when you specify the lang as ruby.

2017-08-16 21:33 UTC, ghoneycutt commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
what does this do?

2017-08-16 21:39 UTC, ghoneycutt commented on README.md
> +## `rizzo compile_test`
This functionality can wait until the next release. The first release should just handle generating the Vagrantfile

2017-08-16 21:47 UTC, ghoneycutt commented on spec/rzo_spec.rb
> +  xit 'does something useful' do
we could have a couple `.rizzo.json` files and see that the generated Vagrantfile matches a fixture.

2017-08-16 21:49 UTC, ghoneycutt commented on rzo.gemspec
> +  spec.licenses      = ['Apache 2.0']
I think this should be `Apache-2.0` to conform with SPDX

2017-08-16 21:50 UTC, ghoneycutt commented on rzo.gemspec
> +  spec.authors       = ['Garrett Honeycutt']
```ruby
spec.authors = ['Garrett Honeycutt', 'Jeff McCune']
```

2017-08-16 21:51 UTC, ghoneycutt commented on rzo.gemspec
> +  spec.email         = ['garrett@learnpuppet.com']
`code@learnpuppet.com`

2017-08-16 21:51 UTC, jeffmccune commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
No idea, it was part of the skeleton generated by `bundle gem rzo`.  I'll remove it.

2017-08-16 21:51 UTC, jeffmccune commented on .travis.yml
> +before_install: gem install bundler -v 1.15.3
Good to know, it was part of the skeleton generated by `bundle gem rzo`.  I'll remove it.

2017-08-16 21:51 UTC, jeffmccune commented on .travis.yml
>    - 2.1.9
Will do.

2017-08-16 21:52 UTC, ghoneycutt commented on rzo.gemspec
> +  spec.summary       = 'rzo - Layered Puppet control repositories in Vagrant'
`Rizzo (rzo) is a tool for working with Vagrant and layered Puppet control repos`

2017-08-16 22:00 UTC, jeffmccune commented
> rzo generate should create the Vagrantfile instead of having to run bundle exec rzo generate > Vagrantfile

Fixed, generate writes to Vagrantfile by default, allows writing to STDOUT

2017-08-16 22:03 UTC, jeffmccune commented on rzo.gemspec
> +  spec.summary       = 'rzo - Layered Puppet control repositories in Vagrant'
Fixed

2017-08-16 22:05 UTC, jeffmccune commented on rzo.gemspec
> +  spec.email         = ['garrett@learnpuppet.com']
Fixed.  FYI, also added myself as an author.

2017-08-16 22:05 UTC, jeffmccune commented on rzo.gemspec
> +  spec.licenses      = ['Apache 2.0']
Fixed

2017-08-16 22:05 UTC, jeffmccune commented on spec/rzo_spec.rb
> +  xit 'does something useful' do
Will add and make travis happy.

2017-08-16 22:05 UTC, jeffmccune commented on README.md
> +## `rizzo compile_test`
Roger, wilco.

2017-08-16 22:06 UTC, jeffmccune commented on README.md
> +`spec/spec_helper.rb` will need at least the following.
Going to push the spec_helper changes to a subsequent release unless you want it in this PR.

2017-08-17 00:25 UTC, jeffmccune commented
This is good to go.  Only thing missing mentioned in the review is some end-to-end testing given .rizzo.json inputs asserting against the Vagrantfile output.

2017-08-17 00:26 UTC, jeffmccune commented on rzo.gemspec
> +  spec.authors       = ['Garrett Honeycutt']
Fixed

2017-08-18 01:02 UTC, jeffmccune commented
End-to-end tests have been added.  This should be ready for merge.

2017-08-18 18:26 UTC, ghoneycutt commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
The above still needs to be removed

2017-08-18 18:28 UTC, ghoneycutt commented on lib/rzo/trollop.rb
> +# lib/trollop.rb -- trollop command-line processing library
Curious why this code is copy/pasted here instead of us calling out to a library in the trollop gem

2017-08-18 18:30 UTC, ghoneycutt commented on spec/fixtures/_complete_rizzo.json
> +      "name": "axpetl-app",
all of these names seem a little too close to home. Let's just pick a few nodes with names like puppet, web, app and db with hostnames like puppet.dev.example.com

2017-08-18 18:33 UTC, ghoneycutt commented on rzo.gemspec
> +  spec.email         = ['garrett@learnpuppet.com']
i dont see the email / author updates

2017-08-18 18:34 UTC, ghoneycutt commented
The README should also be cleaned up so it just documents what the program does and removes my ideas on what it could do.

Would be nice to put the output of `rzo --help` in the README, too.

2017-08-18 19:25 UTC, jeffmccune commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
Removed.

2017-08-18 19:26 UTC, jeffmccune commented on rzo.gemspec
> +  spec.authors       = ['Garrett Honeycutt']
Hrm, a patch seems to have gotten lost in my rebase.  Fixing this again now.

2017-08-18 19:28 UTC, jeffmccune commented on rzo.gemspec
> +  spec.email         = ['garrett@learnpuppet.com']
Fixed for real.

2017-08-18 19:28 UTC, jeffmccune commented on rzo.gemspec
> +  spec.summary       = 'rzo - Layered Puppet control repositories in Vagrant'
Fixed for real.

2017-08-18 19:29 UTC, jeffmccune commented on lib/rzo/trollop.rb
> +# lib/trollop.rb -- trollop command-line processing library
It's based on my experience working with Trollop in Puppet core.  Trollop is designed to be vendored, and it avoids issues in the situation two different command line utilities depend on different versions of Trollop.

2017-08-18 19:34 UTC, jeffmccune commented on spec/fixtures/_complete_rizzo.json
> +      "name": "axpetl-app",
Fixed.

2017-08-18 19:36 UTC, ghoneycutt commented on rzo.gemspec
> +  if spec.respond_to?(:metadata)
doesn't this have to be removed so I can release the gem?

2017-08-18 19:39 UTC, jeffmccune commented on rzo.gemspec
> +  if spec.respond_to?(:metadata)
I'm not 100% sure, but it definitely looks that way.  I set the allowed push host to `https://rubygems.org`.

2017-08-18 19:43 UTC, ghoneycutt requested changes

2017-08-18 19:43 UTC, ghoneycutt commented on README.md
> +### prep
readme needs cleaned up

2017-08-18 19:43 UTC, ghoneycutt commented on lib/rzo/app/templates/Vagrantfile.erb
> +
A line with the version of rzo, something like `This file was generated with Rizzo v0.1.0 - https://github.com/ghoneycutt/rizzo`

2017-08-18 19:43 UTC, ghoneycutt commented on lib/rzo/app/templates/environment.conf.erb
> +# Each environment can have an environment.conf file. Its settings will only
same generated by line as in the Vagrantfile

2017-08-18 19:43 UTC, ghoneycutt commented on lib/rzo/trollop.rb
> +# lib/trollop.rb -- trollop command-line processing library
Makes sense. Could you post a sentence at the top of the file that explains why this was vendored.

2017-08-18 19:55 UTC, jeffmccune commented on lib/rzo/app/templates/environment.conf.erb
> +# Each environment can have an environment.conf file. Its settings will only
I'm actually going to remove this template, the environment.conf is inlined in the generated Vagrantfile.  For example:

```ruby
config.vm.provision 'shell', inline: "echo 'modulepath = ./modules:./puppetdata/modules:./ghoneycutt/modules' > /tmp/bootstrap_puppet4/environment.conf"
```

This was a lot easier than managing different environment files for different VM types.

2017-08-18 20:04 UTC, jeffmccune commented on lib/rzo/app/templates/Vagrantfile.erb
> +
Added.  Looks like:

```
# This file generated with Rizzo 0.1.0 on 2017-08-18 13:00:09 -0700
# https://github.com/ghoneycutt/rizzo
Vagrant.configure(2) do |config|
```

2017-08-18 20:06 UTC, jeffmccune commented on README.md
> +### prep
Readme has been cleaned up

2017-08-18 20:11 UTC, ghoneycutt commented on lib/rzo/app/templates/environment.conf.erb
> +# Each environment can have an environment.conf file. Its settings will only
perhaps it should just do this within the puppetmaster, so `/etc/puppetlabs/code/environment.conf` or wherever it is on the host.

2017-08-18 22:24 UTC, jeffmccune commented on lib/rzo/app/templates/environment.conf.erb
> +# Each environment can have an environment.conf file. Its settings will only
The rizzo generate command adds that inline provision shell command only for puppetmaster nodes.  All the other nodes have the line omitted.

Is that what you meant?

2017-08-18 22:38 UTC, jeffmccune commented on lib/rzo/app/templates/environment.conf.erb
> +# Each environment can have an environment.conf file. Its settings will only
Just as an FYI too, the bootstrap script installs the file using:

```shell
install -o root -g puppet -m 0644 ${BASE_DIR}/environment.conf ${PUPPET_ENVS}/${ENVIRONMENT}/environment.conf
```

This evaluates to:

```
install -o root -g puppet -m 0644 \
  /tmp/bootstrap_puppet4/environment.conf \
  /etc/puppetlabs/code/environments/production/environment.conf
```

2017-08-23 03:55 UTC, ghoneycutt approved these changes

2017-08-23 03:55 UTC, merged